#! /bin/sh
#
for pid in /proc/[0-9]*
do
	cd ${pid}/task || continue
	for thread in [0-9]*
	do
		status=$(cat ${thread}/stat 2>/dev/null) || continue
		command=$(cat ${thread}/comm 2>/dev/null) || continue
		status=${status##*)}
		scheduling=$(echo ${status} | awk '{print $38, $39}')
		priority=${scheduling%% *}

		# sched(7):
		# Processes scheduled under one of the real-time policies
		# (SCHED_FIFO, SCHED_RR) have a sched_priority value in
		# the range 1 (low) to 99 (high).

		if [ ${priority} -lt 1 ]; then continue; fi
		policy=${scheduling##* }
		if [ "$policy" = "1" ]
		then
			scheduler="FIFO"
		elif [ "$policy" = "2" ]
		then
			scheduler=" RR "
		else
			scheduler=" ?? "
		fi
		printf "${scheduler}/%2d [%d] (${command})\n" ${priority} ${thread}
	done
done
